languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "见字如面，欢迎浏览文刀的技术博客！"

[params]
  displayName = "ZH"
  isoCode = "zh-CN"
  # logo = "img/logo.png"

[params.author]
  name = "文刀"
  image = "img/profile.jpg"
  headline = "语音算法工程师 / Agent爱好者"
  bio = "专注于音频理解和声学感知。"
  links = [
    { github = "https://github.com/WendaoSolemn" },
    { email = "yueliu520@gmail.com" },
  ]
